# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jawshytech

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_345a8d7f03b74707a70435a754dcadc5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b3053903796149de8765269fb509b724 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_345a8d7f03b74707a70435a754dcadc5 }}/chrislusf/seaweedfs:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jawshytech'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7e1e48ea33934d73ab6760fb94dea6f5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_345a8d7f03b74707a70435a754dcadc5 }}/chrislusf/seaweedfs:${{ github.sha }}'